version: '3'

networks:
  trazipnet:

volumes:
  db_data:

services:
  db:
    image: postgres:9.6.2
    networks:
    - trazipnet
    environment:
    - POSTGRES_USER=trazip
    - POSTGRES_PASSWORD=trazip
    - POSTGRES_DB=trazip
    volumes:
    - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.10
    networks:
    - trazipnet
    volumes:
    - ./configs/nginx/conf.d:/etc/nginx/conf.d
    ports:
    - "8000:80"
    depends_on:
    - web

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
    - db
    networks:
    - trazipnet
    volumes:
    - .:/src
    environment:
    - DEBUG=false
    - POSTGRES_USER=trazip
    - POSTGRES_PASSWORD=trazip
    - POSTGRES_DB=trazip
    - POSTGRES_HOST=db
    - POSTGRES_PORT=5432
    